# Generated by Django 5.2.8 on 2025-11-27 15:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adoption_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='adoption_requests.adoptionrequest')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
